### ISSUE TITLE
2 FPD & 2 reflected xss vulnerability in web app

### ISSUE THREAD

**Issue by 0xbsec** [approach0/search-engine#12]
## Reflected xss:
1- https://approach0.xyz/search/?q=test&p=1%22%3E%3Csvg/onload=alert(/test/)%3E
2- https://approach0.xyz/search/?q=%24test%22%3E%3Csvg/onload=alert(/test/)%3E&p=1
**fix**: sanitize input ( try `htmlspecialchars($string, ENT_QUOTES, 'UTF-8');` and check [here](https://www.owasp.org/index.php/XSS_%28Cross_Site_Scripting%29_Prevention_Cheat_Sheet) ) from params `q` and `p` in [L149-150 index.php](https://github.com/approach0/search-engine/blob/master/demo/web/index.php#L149-L150).
## Full path disclosure:
1- https://approach0.xyz/demo/search-relay.php?p=1&q[]=test
2- https://approach0.xyz/demo/?q[]=test&p=1
*1* is caused by `strlen($qry_str)` in [search-relay.php L45](https://github.com/approach0/search-engine/blob/master/demo/web/search-relay.php#L45), to fix it: use `is_scalar` [when checking `$_GET['q']`](https://github.com/approach0/search-engine/blob/master/demo/web/search-relay.php#L77).
<img width="784" alt="screen shot 2016-09-12 at 6 10 49 pm" src="https://cloud.githubusercontent.com/assets/8887221/18441436/be8fecb2-7915-11e6-97c2-354192c03067.png">

**Comment by t-k-** [comment]
Hmm... I did not even have a thought on security aspect yet. (I do not have much experience also) 
But thank you for pointing it out, I am willing to spend some time on this issue. Welcome any PR too!

**Comment by t-k-** [comment]
Fixed (977ad40b13589cfbfcbabefd3573f251528de83a).

**Comment by 0xbsec** [comment]
> My Chromium (52.0.2743.116) is not affected by xss URLs, Firefox is though.

That's because of Chrome xss filter.

The issues provided above look fixed now.
Good luck!

**Comment by t-k-** [comment]
Good to learn this, thank you!
