### ISSUE TITLE
小建议

### ISSUE THREAD

**Issue by bedreamer** [approach0/search-engine#17]
基础库中引用的C库可以使用简单函数名替换。例如：
printf 的使用，如果在库中频繁使用printf功能，则建议使用类似如下的方式替换,
`static inline int lib_printf(const char *fmt, ...) {
     ....
     printf( some string );
     ....
}`
这样有个好处，库被别人引用时，可以定制是否需要输出。

**Comment by t-k-** [comment]
谢谢大湿的建议。我现在更倾向于用宏直接写在 .c 文件里控制打印。当然这样看起来不是很美观。但是有一些好处：

1. [这种情况](https://github.com/approach0/search-engine/blob/de6d235f7d49ffd100c59464665cbdb50e0148ab/search/search.c#L122-L134)宏不但可以控制打印语句，还可以进一步控制和打印相关的其他语句。

2.[有些情况](https://github.com/approach0/search-engine/blob/de6d235f7d49ffd100c59464665cbdb50e0148ab/searchd/run/searchd.c#L24-L39)需要 log 的时候宏也可以控制。如果使用类似 lib_printf 和 lib_fprintf 的当然也可以，但这样增加了两个新的东西，对比使用宏配合 printf 和 fprintf 这样公共所知的东西，用宏控制说不定更有可读性。

**Comment by t-k-** [comment]
暂时先关了这个 issue，下次尽量用英文在 Github 上交流。加油！
