### ISSUE TITLE
Forced title search

### ISSUE THREAD

**Issue by whoinoi** [approach0/search-engine#21]
I really like the search, but right now it's way to broad. It gives too many useless results.

One thing that would greatly help is a "forced title" setting to force the title to match the keywords and expressions.

What's nice about the loose math expression search is that variable names don't matter (for example $y^2$ or $x^2$ yield the same result). However there are also some problems with that since the search for $x^2$ matches also expressions like $\mathbb{R}^2$ which is unwanted. But I can imagine that it is difficult to come up with some good ruleset, so that for example $Q^2$ (where $\mathbb{Q}^2$ is intended) matches with $\mathbb{R}^2$ but $x^2$ doesn't.

**Comment by t-k-** [comment]
Thank you for your thought and feedback, Approach0 is currently a demo and prototype than a product. Focus is still on the improvement of core algorithm, such as the way math expression is retrieved and how to improve its efficiency. I will think about those features with regarding to being a product, in a later stage.
