### ISSUE TITLE
Server is down

### ISSUE THREAD

**Issue by VincentTam** [approach0/search-engine#24]
The webpage says

> Opps! Server is down right now, but will be back shortly. (return code #101)

**Comment by t-k-** [comment]
Thank you for reminding me here. It is because a reboot scheduled by my VPS server:

> Your Linode(s) have been assigned maintenance windows during which they will be rebooted. This maintenance is necessary to patch for variants 1 and 2 of the Spectre vulnerability[1]. The scheduled times for these reboots are listed within the Linode Manager[2] in the timezone set in your user's Profile[3]. 
> 
> Your reboot schedule in UTC is as follows: 
> 
> * 2018-05-11 6:00:00 AM UTC - linode2369245

I've already restarted the server. It should work now.
