### ISSUE TITLE
Follow up on the updated Mathquill fork.

### ISSUE THREAD

**Issue by t-k-** [approach0/search-engine#25]
I have built and pulled the forked version of Mathquill from @TheSil, see: 8c51528246a0beed308471a30802d1645b01afb3

Now the \lVert, \lvert, \langle and \rangle can be successfully entered.
And \dots is correctly handled after updating KaTeX.

Here I would welcome anyone to keep adding things into [the list](https://github.com/TheSil/mathquill/commit/b768f871c6e7a612bb7d65d032b4f7e7c85aa115) and send a pull request to the [forked Mathquill](https://github.com/TheSil/mathquill).

@TheSil Thank you again for your help. Feel free to keep working on your forked repo and expand the "subs" there, only if you find other things are missing in that list. I would be more than willing to build your source and merge it into Approach0 online demo.

**Comment by TheSil** [comment]
Added \tfrac support https://github.com/TheSil/mathquill/commit/93d32c38a31aed75d47282f0ccc13f3df144182a . Recent example encountered `\frac{\log(x-\tfrac12\log x)}{\log(x+\tfrac12\log x)}>1-\tfrac1x`.

**Comment by TheSil** [comment]
Also added support for spacing by for example \, in https://github.com/TheSil/mathquill/commit/68b2beb084c561918a93afac11bcd516308fa952 . Simple command to try `(1,2,3)(1:2:3)\ \: \ \, `

**Comment by TheSil** [comment]
The https://github.com/TheSil/mathquill/commit/68b2beb084c561918a93afac11bcd516308fa952 and https://github.com/TheSil/mathquill/commit/695a2fbaa94401b7039dad88dfe04ecbff02497f should also allow use of spaces by `\,`. Motivated by `\displaystyle{\frac{\ln(x-0.5 \ln x)}{\ln(x+0.5 \ln x)} = \frac{\ln x +\ln(1-0.5 \frac{\ln x}{x})}{\ln x+ \ln(1+0.5 \frac{\ln x}{x})} \geq \frac{\ln x- \frac{\ln x}{2x}}{\ln x+\frac{\ln x}{2x}-\frac{\ln^2 x}{4x^2}}} = 1 -\frac{\frac{\ln x}{x}-\frac{\ln^2 x}{4x^2}}{\ln x+ \frac{\ln x}{2x}-\frac{\ln^2 x}{4x^2}}`.

**Comment by TheSil** [comment]
And here is support for mod like operator (\bmod, \pmod): https://github.com/TheSil/mathquill/commit/ed03034d87f3647461acecd00a5faf806603c868 . Again some example `\gcd(3\cdot 3 + 1, 3\cdot 5 + 1) \equiv 2 \pmod{3}`

**Comment by TheSil** [comment]
Added \tfrac support TheSil/mathquill@93d32c3 . Recent example encountered \frac{\log(x-\tfrac12\log x)}{\log(x+\tfrac12\log x)}>1-\tfrac1x.

The TheSil/mathquill@68b2beb, TheSil/mathquill@695a2fb and TheSil/mathquill@cf88102 should also allow use of spaces by \,. Motivated by \frac{\log \left(x-\frac{1}{2}\log (x)\right)}{\log \left(x+\frac{1}{2}\log (x)\right)}=1-\frac{1}{x}+\frac{1}{2\, x^2}-\frac{2 \log ^2\left({x}\right)+3 \log \left({x}\right)+6}{24\, x^3}+O\left(\frac{1}{x^4}\right).

And here is support for mod like operator (\bmod, \pmod): TheSil/mathquill@ed03034 . Again some example \gcd(3\cdot 3 + 1, 3\cdot 5 + 1) \equiv 2 \pmod{3}

Supporint \nmid (not dividing) operator in https://github.com/TheSil/mathquill/commit/b47f0a629ead1ca6b1ddb2295058eec891bc08a4 .

**Comment by TheSil** [comment]
Run into quite some unsupported commands recently, surprised they are not in mathquill. Anyway here is summary:

`\tfrac` support TheSil/mathquill@93d32c3 . Recent example encountered `\frac{\log(x-\tfrac12\log x)}{\log(x+\tfrac12\log x)}>1-\tfrac1x`.

The TheSil/mathquill@68b2beb, TheSil/mathquill@695a2fb and TheSil/mathquill@cf88102 should also allow use of spaces by `\,`, `\;`, etc. Motivated by `\frac{\log \left(x-\frac{1}{2}\log (x)\right)}{\log \left(x+\frac{1}{2}\log (x)\right)}=1-\frac{1}{x}+\frac{1}{2\, x^2}-\frac{2 \log ^2\left({x}\right)+3 \log \left({x}\right)+6}{24\, x^3}+O\left(\frac{1}{x^4}\right)`.

`mod` like operator (`\bmod`, `\pmod`): TheSil/mathquill@ed03034 . Again some example `\gcd(3\cdot 3 + 1, 3\cdot 5 + 1) \equiv 2 \pmod{3}`

`\nmid` (not dividing) operator in https://github.com/TheSil/mathquill/commit/b47f0a629ead1ca6b1ddb2295058eec891bc08a4 .

My TODO list:


~~\iiint, \iint~~ - done in https://github.com/TheSil/mathquill/commit/4daf8b313c0a056be8711273917fe02dc620ee2b
\overbrace, \underbrace
~~\underleftarrow, \underrightarrow, \underleftrightarrow~~ - done in https://github.com/TheSil/mathquill/commit/0c92e0574a0e20fbf1f244964d15081dc0c11387
\xleftarrow, \xrightarrow
~~\fbox, \boxed~~ -done in https://github.com/TheSil/mathquill/commit/6cc8042faefadce5f4677d281de4f6347af62c17
~~\color~~ - done in https://github.com/TheSil/mathquill/commit/2a2a532f9be557fe3e118fcccacd8ae835fe8a6e
~~\cancel~~ - done in https://github.com/TheSil/mathquill/commit/d1420740b7053d828d55a009d5c52488a7cc0483

**Comment by t-k-** [comment]
@TheSil Thank you for your work, I will pull these fixes now.
