### ISSUE TITLE
Is there a public web-demo for approach0?

### ISSUE THREAD

**Issue by physikerwelt** [approach0/search-engine#26]

**Comment by physikerwelt** [comment]
A found it https://approach0.xyz/search/

**Comment by physikerwelt** [comment]
by the way, I started to compile a list of functional math search engines. Currently, this list is
* https://dlmf.nist.gov/search/search?q=%5CEulerGamma
* https://zbmath.org/formulae/
* https://www.searchonmath.com/
* https://approach0.xyz/search/?q=%24%5CGamma%24&p=1

**Comment by t-k-** [comment]
Just a comment here. The current online version and index are not updated for years.  I am currently working on a new version which hopefully will be available online in just one or two months.

**Comment by t-k-** [comment]
The new version is already online. I will close this issue. @physikerwelt

BTW. Your list looks good to me, though there are others that I am aware of, but most of them are not open systems.
