### ISSUE TITLE
Filtering results by source

### ISSUE THREAD

**Issue by TheSil** [approach0/search-engine#29]
I thought I would create an issue for this. Sometimes it would be nice to filter which sources I want to display (some other MSE users expressed this request).

**Comment by t-k-** [comment]
I will keep this on my TODO list.

**Comment by TheSil** [comment]
Maybe also worth considering to add the target  site icon somewhere next to the link even in unfiltered version, just to aid visually the user so that he does not need to parse the url to see from where it is. 

Like some of these (mad paintbrush skills):
![variant1](https://user-images.githubusercontent.com/1452077/102783376-1a969480-439b-11eb-8d4d-3fbb8fb8b78e.png)
![variant2](https://user-images.githubusercontent.com/1452077/102783385-1cf8ee80-439b-11eb-88e9-dda0ff071ad3.png)
![variant3](https://user-images.githubusercontent.com/1452077/102783390-1ec2b200-439b-11eb-8a11-1d5ee072714e.png)

(personally i like the last one as it seems the most minimal, some additional space could be also obtained by hiding the "http://" and "https://" part of the link)

**Comment by w32zhong** [comment]
@TheSil I also prefer the last one. I have made those changes in the [UI repo](https://github.com/approach0/ui-approach0) (commit 1995e8a). With that, I am about to deploy it online, you can check it out in a few minutes...

I remember last time you have brought up this idea but I thought that would hurt the general purpose if people use a0 engine to host other data sources, but currently we only get 2 data sources and as long as we both feel like it, why not?

**Comment by TheSil** [comment]
Thanks for the update, it looks very good!

As for the genericity, I suppose this is a generic user requirement, just the logos would be perhaps different (or absent) for specific data sources. However how to do this genericity in the code, that I am not sure (i am not a web developer unfortunately), but seems like the logos would have to be part of some specific data source metadata that they provide to the framework? Idk.

**Comment by w32zhong** [comment]
Right, if they need icons to be displayed for another data source, they can modify this repo, but I have made it in vue-if-else directives so if they do not specify, it won't hold the place. I think it is good, it is just an option.

**Comment by w32zhong** [comment]
Solved in the latest private code.
