### ISSUE TITLE
cannot visit resource webpage 

### ISSUE THREAD

**Issue by moonlightlane** [approach0/search-engine#31]
Hello! I was trying to access http://approach0.xyz/ecir2019/ to reproduce results for the ecir2019 ntcir math formula retrieval results. 

When I was trying to access the above webpage, I got a "502 bad gateway" error. 

Can I download the resources elsewhere, especially the `corpus.txt` file, to be able to run the indexer? 

Thanks!

**Comment by t-k-** [comment]
@moonlightlane Hi, sorry for my late response. Indeed I did not copy those data when I migrate my VPS server, I am sorry about that. Thankfully I still keep them in my hard disk, I will upload them to Google drive and update the ECIR2019 README file. BTW, you can also follow our ECIR2020 paper where we have a newer and larger dataset (also from MSE) available for downloading. Thanks for reporting.

**Comment by t-k-** [comment]
Here is google drive link: https://drive.google.com/file/d/1kaNjozKJhDUnCevw4fsrmYdsw8Wixkn2/view?usp=sharing
