### ISSUE TITLE
How to search a formula locally?

### ISSUE THREAD

**Issue by LMC63** [approach0/search-engine#34]
@t-k- Dear sir, thanks a lot for your contribution. For the notes aren’t very detailed, I wonder if I want to search formula form my local database, how can I use your code? 

 I will be grateful for your reply.

**Comment by w32zhong** [comment]
Check out the python binding: https://github.com/approach0/pya0

You can find example usages on this Colab: https://colab.research.google.com/drive/1lhG5KlXogG-ulIPF9wEwHeHFLJvx__H-?usp=sharing
