### ISSUE TITLE
Questions about datasets

### ISSUE THREAD

**Issue by popcorn31029** [approach0/search-engine#37]
Dear author, excuse me, I have two questions : 
1. Where did you get the datasets? (topics.txt, NTCIR12_MathWiki-qrels_judge.dat, NTCIR12_latex_expressions.txt, all.dat in the google drive)
2. What is the meaning of the datasets? (topics.txt, NTCIR12_MathWiki-qrels_judge.dat, NTCIR12_latex_expressions.txt, all.dat in the google drive)
Thanks for your any help!

**Comment by w32zhong** [comment]
they are from NTCIR-12 math search task organizers. you can find more info here: https://ntcir-math.nii.ac.jp/
